use_frameworks!

platform :ios, '11.0'

target 'PhotoManager_Example' do
  pod 'PhotoManager', :path => '../'
  pod 'MediaEditorManager'
  pod 'SliderIndicator'
  pod 'Util_V'
  pod 'SnapKit'
  pod 'ContentSizeView'
  pod 'LookinServer'
end
